[toolchain]
package_manager = "bun"

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor = "62sSE2g4sBQ7Av2mmhasTDP3zWA7QBpf9wa7nDN1rwj4"

[programs.devnet]
anchor = "62sSE2g4sBQ7Av2mmhasTDP3zWA7QBpf9wa7nDN1rwj4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/devnet-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
